// AUTO-GENERATED by scripts/genThemes.mjs — do not edit by hand.
export interface ThemeDef { id: string; name: string; group: string; surface: string; accent: string; }
export const THEMES: ThemeDef[] = [
  { id: 'terminal', name: "Terminal", group: "Platform", surface: '#1f2123', accent: '#E5E5E5' },
  { id: 'arbor', name: "Arbor", group: "Platform", surface: '#17261f', accent: '#3F9C79' },
  { id: 'skyvision', name: "SkyVision", group: "Platform", surface: '#192229', accent: '#6A93B5' },
  { id: 'pinpoint', name: "Pinpoint", group: "Platform", surface: '#2a2218', accent: '#C79350' },
  { id: 'expiry', name: "Expiry", group: "Mechanics", surface: '#2a1c13', accent: '#E85A00' },
  { id: 'tape', name: "Tape", group: "Mechanics", surface: '#281515', accent: '#C84848' },
  { id: 'flow', name: "Flow", group: "Mechanics", surface: '#161c2d', accent: '#4A6CC0' },
  { id: 'dealer', name: "Dealer", group: "Mechanics", surface: '#142329', accent: '#4A9BC4' },
  { id: 'gamma', name: "Gamma", group: "Mechanics", surface: '#211726', accent: '#8A5AA0' },
  { id: 'charm', name: "Charm", group: "Mechanics", surface: '#281a20', accent: '#A06880' },
  { id: 'vanna', name: "Vanna", group: "Mechanics", surface: '#232919', accent: '#7A9A50' },
  { id: 'prairie', name: "Prairie", group: "Territory", surface: '#292419', accent: '#8A7040' },
  { id: 'ramsey', name: "Ramsey", group: "Territory", surface: '#1c262c', accent: '#5F8296' },
  { id: 'pitch', name: "Pitch", group: "Aesthetic", surface: '#14141f', accent: '#6A93B5' },
  { id: 'tungsten', name: "Tungsten", group: "Aesthetic", surface: '#222325', accent: '#A6ACB2' },
];
