/**
 * Theme generator — emits a complete, token-based theme library.
 * Each theme overrides the design tokens the app already consumes
 * (--bg-base, --surface[-2/-3], --border[-strong], --text-primary/secondary/tertiary,
 * --accent-color, --grid-dot). Semantic colors (--success/danger/warning/info) are
 * intentionally NOT themed so up/down stays readable on a trading screen.
 *
 * Palettes are derived from a single (hue, saturation, base-lightness, accent) seed
 * via HSL math, so every theme is internally harmonized and meets AA text contrast.
 * Run:  node scripts/genThemes.mjs   ->   src/themes.css  +  src/lib/themes.generated.ts
 */
import { writeFileSync } from 'fs';

/* ---- color helpers ---- */
const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));
function hslToHex(h, s, l) {
  h = ((h % 360) + 360) % 360; s = clamp(s, 0, 100) / 100; l = clamp(l, 0, 100) / 100;
  const c = (1 - Math.abs(2 * l - 1)) * s, x = c * (1 - Math.abs(((h / 60) % 2) - 1)), m = l - c / 2;
  let r = 0, g = 0, b = 0;
  if (h < 60) [r, g, b] = [c, x, 0]; else if (h < 120) [r, g, b] = [x, c, 0];
  else if (h < 180) [r, g, b] = [0, c, x]; else if (h < 240) [r, g, b] = [0, x, c];
  else if (h < 300) [r, g, b] = [x, 0, c]; else [r, g, b] = [c, 0, x];
  const to = (n) => Math.round((n + m) * 255).toString(16).padStart(2, '0');
  return `#${to(r)}${to(g)}${to(b)}`;
}
const rgba = (h, s, l, a) => {
  const hex = hslToHex(h, s, l);
  const n = parseInt(hex.slice(1), 16);
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${a})`;
};

/* ---- token derivation from a seed ---- */
function tokensFor(seed) {
  const [, , , mode, h, s, lBase, accent] = seed;
  if (mode === 'light') {
    const ts = Math.min(s, 22);
    return {
      '--bg-base': hslToHex(h, ts, 96),
      '--surface': hslToHex(h, ts * 0.5, 99),
      '--surface-2': hslToHex(h, ts, 93),
      '--surface-3': hslToHex(h, ts, 88),
      '--border': rgba(h, 30, 30, 0.12),
      '--border-strong': rgba(h, 30, 30, 0.22),
      '--text-primary': hslToHex(h, 24, 15),
      '--text-secondary': hslToHex(h, 18, 32),
      '--text-tertiary': hslToHex(h, 14, 45),
      '--accent-color': accent,
      '--grid-dot': hslToHex(h, ts, 90),
      'color-scheme': 'light',
    };
  }
  // dark
  return {
    '--bg-base': hslToHex(h, s, lBase),
    '--surface': hslToHex(h, s * 0.92, lBase + 5),
    '--surface-2': hslToHex(h, s * 0.85, lBase + 9),
    '--surface-3': hslToHex(h, s * 0.8, lBase + 14),
    '--border': rgba(h, Math.min(s, 45), 78, 0.10),
    '--border-strong': rgba(h, Math.min(s, 45), 80, 0.20),
    '--text-primary': hslToHex(h, Math.min(s, 16), 93),
    '--text-secondary': hslToHex(h, Math.min(s, 13), 77),
    '--text-tertiary': hslToHex(h, Math.min(s, 11), 59),
    '--accent-color': accent,
    '--grid-dot': hslToHex(h, s, lBase + 4),
    'color-scheme': 'dark',
  };
}

/* ---- seeds: [id, name, group, mode, hue, sat, baseL, accent] ---- */
const SEEDS = [
  // Platform — the engines
  ['terminal','Terminal','Platform','dark',220,6,8,'#E5E5E5'],
  ['arbor','Arbor','Platform','dark',153,26,7,'#3F9C79'],
  ['skyvision','SkyVision','Platform','dark',207,26,8,'#6A93B5'],
  ['pinpoint','Pinpoint','Platform','dark',34,30,8,'#C79350'],
  // Mechanics — 0DTE / SPX vocabulary
  ['expiry','Expiry','Mechanics','dark',23,40,7,'#E85A00'],
  ['tape','Tape','Mechanics','dark',0,34,7,'#C84848'],
  ['flow','Flow','Mechanics','dark',224,38,8,'#4A6CC0'],
  ['dealer','Dealer','Mechanics','dark',197,38,7,'#4A9BC4'],
  ['gamma','Gamma','Mechanics','dark',280,28,7,'#8A5AA0'],
  ['charm','Charm','Mechanics','dark',336,24,8,'#A06880'],
  ['vanna','Vanna','Mechanics','dark',84,26,8,'#7A9A50'],
  // Territory — Minnesota / Frogtown
  ['prairie','Prairie','Territory','dark',40,26,8,'#8A7040'],
  ['ramsey','Ramsey','Territory','dark',202,24,9,'#5F8296'],
  // Aesthetic — mood, not hue
  ['pitch','Pitch','Aesthetic','dark',240,24,5,'#6A93B5'],
  ['tungsten','Tungsten','Aesthetic','dark',216,4,9,'#A6ACB2'],
];

/* ---- emit ---- */
let css = `/* AUTO-GENERATED by scripts/genThemes.mjs — do not edit by hand. ${SEEDS.length} themes.
   Token-based: each theme overrides only the design tokens the app consumes.
   Semantic colors (--success/--danger/--warning/--info) inherit from :root so
   up/down stays readable on every theme. */\n\n`;

for (const seed of SEEDS) {
  const [id] = seed;
  const t = tokensFor(seed);
  const body = Object.entries(t).map(([k, v]) => `${k}: ${v};`).join(' ');
  css += `[data-theme="${id}"] { ${body} }\n`;
}

// Legacy hardcoded page-black -> themed base, so the app frame follows the theme.
css += `\n/* Make the app frame's hardcoded black follow the active theme's base. */\n`;
css += `[data-theme] .theme-bg-base { background-color: var(--bg-base) !important; }\n`;

writeFileSync(new URL('../src/themes.css', import.meta.url), css);

const ts = `// AUTO-GENERATED by scripts/genThemes.mjs — do not edit by hand.\n`
  + `export interface ThemeDef { id: string; name: string; group: string; surface: string; accent: string; }\n`
  + `export const THEMES: ThemeDef[] = [\n`
  + SEEDS.map((s) => {
      const t = tokensFor(s);
      return `  { id: '${s[0]}', name: ${JSON.stringify(s[1])}, group: ${JSON.stringify(s[2])}, surface: '${t['--surface']}', accent: '${s[7]}' },`;
    }).join('\n')
  + `\n];\n`;

writeFileSync(new URL('../src/lib/themes.generated.ts', import.meta.url), ts);

console.log(`Generated ${SEEDS.length} themes -> src/themes.css + src/lib/themes.generated.ts`);
const groups = [...new Set(SEEDS.map((s) => s[2]))];
console.log('Groups:', groups.join(', '));
